name: workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    if: github.event_name == 'pull_request'
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
        with:
          files: ./content
          args: --minAlertLevel=error
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      - name: Build
        run: hugo --minify
      # Create artifact
      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: public
          path: public
  deploy:
    needs: build
    name: deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    # Get the artifact from the build, then deploy it to GitHub Pages
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: public
          path: public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
